import { z } from 'zod';
import type { Database } from '@/types/supabase';

// Enum types from database
const ticketStatusEnum = ['open', 'in_progress', 'pending', 'resolved', 'closed'] as const;
const ticketPriorityEnum = ['low', 'medium', 'high', 'urgent'] as const;

type TicketStatus = Database['public']['Enums']['ticket_status'];
type TicketPriority = Database['public']['Enums']['ticket_priority'];

/**
 * Schema for validating ticket creation/update forms
 * This ensures that the data matches our types at runtime
 */
export const ticketSchema = z.object({
  id: z.string().uuid().optional(),
  organization_id: z.string().uuid(),
  customer_id: z.string().uuid(),
  assigned_to: z.string().uuid().nullable(),
  title: z.string().min(1),
  description: z.string().nullable(),
  status: z.enum(ticketStatusEnum).nullable(),
  priority: z.enum(ticketPriorityEnum).nullable(),
  metadata: z.record(z.unknown()).nullable(),
  created_at: z.string().datetime().nullable(),
  updated_at: z.string().datetime().nullable(),
  closed_at: z.string().datetime().nullable(),
  last_activity_at: z.string().datetime().nullable(),
});

/**
 * Schema for creating a new ticket
 * Omits fields that are generated by the database
 */
export const createTicketSchema = z.object({
  title: z.string().min(1),
  description: z.string(),
  priority: z.enum(ticketPriorityEnum),
});

/**
 * Schema for updating an existing ticket
 */
export const updateTicketSchema = z.object({
  title: z.string().min(1).optional(),
  description: z.string().optional(),
  priority: z.enum(ticketPriorityEnum).optional(),
  status: z.enum(ticketStatusEnum).optional(),
  assigned_to: z.string().uuid().nullable().optional(),
});

/**
 * Schema for ticket messages
 */
export const ticketMessageSchema = z.object({
  id: z.string().uuid().optional(),
  ticket_id: z.string().uuid(),
  sender_id: z.string().uuid(),
  message: z.string().min(1),
  is_internal: z.boolean().nullable(),
  metadata: z.record(z.unknown()).nullable(),
  created_at: z.string().datetime().nullable(),
  updated_at: z.string().datetime().nullable(),
});
